class Solution:
    def sortedSquares(self, nums: List[int]) -> List[int]:
        """ hint consider this question as a parabola which was generated by squaring a number
        now we want to sort two extreme values which will be largest numbers at extremes"""

        left, right = 0, len(nums)-1
        result = []
        while left<=right:
            if abs(nums[left])<=abs(nums[right]):
                result.append(nums[right]*nums[right])
                right -= 1
            else:
                result.append(nums[left]*nums[left])
                left += 1
        return result[::-1] # reverse the result for non decreasing order

        